/**
 * Self-hosts the two webfonts the design uses.
 *
 * The stylesheet originally did `@import` from fonts.googleapis.com, which is
 * wrong for this app on three counts:
 *
 *   1. It is a network dependency in an app whose whole promise is that it
 *      works offline. First load with no connection would fall back to system
 *      fonts, and the request 404s on hosts that block the CDN.
 *   2. It leaks a request to a third party on every cold load, which is
 *      exactly the kind of thing a privacy tool should not do.
 *   3. It forces the CSP to allow two external origins, widening it for no
 *      good reason.
 *
 * This downloads only the Latin + Latin-ext subsets (the app has no Cyrillic,
 * Greek, or Vietnamese copy) and writes a local @font-face block, so the CSP
 * can be tightened back to 'self'.
 *
 * Run with:  node tools/fetch-fonts.mjs
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap';

const OUT_DIR = join(process.cwd(), 'fonts');
const OUT_CSS = join(process.cwd(), 'src', 'styles', 'fonts.css');

// Only these subsets are needed for this app's copy.
const KEEP = new Set(['latin', 'latin-ext']);

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`fonts.googleapis.com returned ${r.status}`);
    return r.text();
  });

  // The Google CSS is a flat sequence of: /* subset */ @font-face { ... }
  const blocks = css.split('/*').slice(1);
  const kept = [];
  let downloaded = 0;

  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf('*/')).trim();
    if (!KEEP.has(subset)) continue;

    const face = raw.slice(raw.indexOf('*/') + 2);
    const family = /font-family:\s*'([^']+)'/.exec(face)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(face)?.[1];
    const url = /src:\s*url\(([^)]+)\)/.exec(face)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(face)?.[1];
    if (!family || !url || !weight) continue;

    const filename = `${family.replace(/\s+/g, '-').toLowerCase()}-${weight}-${subset}.woff2`;
    const bytes = Buffer.from(
      await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()),
    );
    writeFileSync(join(OUT_DIR, filename), bytes);
    downloaded += bytes.length;

    kept.push(
      `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('../../fonts/${filename}') format('woff2');\n` +
        (range ? `  unicode-range: ${range};\n` : '') +
        `}`,
    );
    console.log(`  ${filename}  (${(bytes.length / 1024).toFixed(1)} KB)`);
  }

  const header =
    `/* ---------------------------------------------------------------- fonts\n` +
    ` * Self-hosted webfonts. Generated by tools/fetch-fonts.mjs — do not edit\n` +
    ` * by hand. Only the latin and latin-ext subsets are included.\n` +
    ` * Self-hosting keeps the app fully offline-capable and the CSP at 'self'.\n` +
    ` */\n\n`;

  writeFileSync(OUT_CSS, header + kept.join('\n\n') + '\n');

  console.log(
    `\n${kept.length} @font-face rules written to src/styles/fonts.css ` +
      `(${(downloaded / 1024).toFixed(1)} KB total)`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
